# Generated by Django 6.1 on 2026-08-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус оборудования',
                'verbose_name_plural': 'Статусы оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('specifications', models.TextField(blank=True, verbose_name='Технические характеристики')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата поступления')),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Балансовая стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='employees.location', verbose_name='Текущее местонахождение')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='employees.employee', verbose_name='Ответственное лицо')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='equipment.equipmentcategory', verbose_name='Категория')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='equipment.equipmentstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['inventory_number'],
            },
        ),
    ]
