# Generated by Django 6.1 on 2026-08-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('workstations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='workstation',
            field=models.ForeignKey(blank=True, help_text='Если единица входит в сборку — рабочее место или ПК из нескольких компонентов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_items', to='workstations.workstation', verbose_name='Сборка (рабочее место / ПК)'),
        ),
    ]
