# Generated by Django 6.1 on 2026-08-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «АРМ инженера Иванова» или «ПК №5»', max_length=255, verbose_name='Название')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations', to='employees.location', verbose_name='Местонахождение')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations', to='employees.employee', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Сборка (рабочее место / ПК)',
                'verbose_name_plural': 'Сборки (рабочие места / ПК)',
                'ordering': ['name'],
            },
        ),
    ]
