# Generated by Django 6.1 on 2026-08-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код типа')),
                ('template_filename', models.CharField(blank=True, help_text='Имя файла .docx в папке documents/doc_templates/', max_length=255, verbose_name='Файл шаблона')),
                ('number_prefix', models.CharField(blank=True, help_text="Например 'АПП' для акта приёма-передачи", max_length=10, verbose_name='Префикс номера')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Номер')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reason', models.TextField(blank=True, help_text='Используется для актов списания и возврата (состояние, причина списания и т.д.)', verbose_name='Причина/основание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Сгенерированный файл')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_from', to='employees.employee', verbose_name='Передал (сотрудник)')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_from', to='employees.location', verbose_name='Откуда')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_to', to='employees.employee', verbose_name='Принял (сотрудник)')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_to', to='employees.location', verbose_name='Куда')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.document', verbose_name='Документ')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_entries', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Позиция документа',
                'verbose_name_plural': 'Позиции документа',
            },
        ),
    ]
