# Generated by Django 6.1 on 2026-08-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('transfer', 'Передача сотруднику'), ('move', 'Перемещение (смена местонахождения)'), ('repair', 'Отправка в ремонт'), ('return_repair', 'Возврат из ремонта'), ('status_change', 'Изменение статуса'), ('write_off', 'Списание'), ('receipt', 'Поступление (первичная постановка на учёт)'), ('return', 'Возврат оборудования (сдан обратно)')], max_length=20, verbose_name='Тип события')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_events', to='documents.document', verbose_name='Документ-основание')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_events', to='equipment.equipment', verbose_name='Оборудование')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='employees.employee', verbose_name='От сотрудника')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='employees.location', verbose_name='Откуда')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='employees.employee', verbose_name='Кому передано')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='employees.location', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Событие истории',
                'verbose_name_plural': 'История перемещений',
                'ordering': ['-event_date'],
            },
        ),
    ]
