# Generated by Django 6.1 on 2026-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementhistory',
            name='event_type',
            field=models.CharField(choices=[('transfer', 'Передача сотруднику'), ('move', 'Перемещение (смена местонахождения)'), ('repair', 'Отправка в ремонт'), ('return_repair', 'Возврат из ремонта'), ('status_change', 'Изменение статуса'), ('write_off', 'Списание'), ('receipt', 'Поступление (первичная постановка на учёт)'), ('return', 'Возврат оборудования (сдан обратно)'), ('assembly', 'Включение в сборку (акт сборки)')], max_length=20, verbose_name='Тип события'),
        ),
    ]
